insert into countries (iso2, name, region, currency, ecowas, afcfta, enabled, pilot) values
('dz', 'Algeria', 'north', 'DZD', false, true, false, false),
('ao', 'Angola', 'south', 'AOA', false, true, false, false),
('bj', 'Benin', 'west', 'XOF', true, true, true, false),
('bw', 'Botswana', 'south', 'BWP', false, true, false, false),
('bf', 'Burkina Faso', 'west', 'XOF', false, true, false, false),
('bi', 'Burundi', 'central', 'BIF', false, true, false, false),
('cv', 'Cabo Verde', 'west', 'CVE', true, true, true, false),
('cm', 'Cameroon', 'central', 'XAF', false, true, false, false),
('cf', 'Central African Republic', 'central', 'XAF', false, true, false, false),
('td', 'Chad', 'central', 'XAF', false, true, false, false),
('km', 'Comoros', 'east', 'KMF', false, true, false, false),
('ci', 'Côte d''Ivoire', 'west', 'XOF', true, true, true, false),
('dj', 'Djibouti', 'east', 'DJF', false, true, false, false),
('cd', 'DR Congo', 'central', 'CDF', false, true, false, false),
('eg', 'Egypt', 'north', 'EGP', false, true, false, false),
('gq', 'Equatorial Guinea', 'central', 'XAF', false, true, false, false),
('er', 'Eritrea', 'east', 'ERN', false, false, false, false),
('sz', 'Eswatini', 'south', 'SZL', false, true, false, false),
('et', 'Ethiopia', 'east', 'ETB', false, true, false, false),
('ga', 'Gabon', 'central', 'XAF', false, true, false, false),
('gh', 'Ghana', 'west', 'GHS', true, true, true, false),
('gn', 'Guinea', 'west', 'GNF', true, true, true, false),
('gw', 'Guinea-Bissau', 'west', 'XOF', true, true, true, false),
('ke', 'Kenya', 'east', 'KES', false, true, false, false),
('ls', 'Lesotho', 'south', 'LSL', false, true, false, false),
('lr', 'Liberia', 'west', 'LRD', true, true, true, false),
('ly', 'Libya', 'north', 'LYD', false, true, false, false),
('mg', 'Madagascar', 'east', 'MGA', false, true, false, false),
('mw', 'Malawi', 'south', 'MWK', false, true, false, false),
('ml', 'Mali', 'west', 'XOF', false, true, false, false),
('mr', 'Mauritania', 'north', 'MRU', false, true, false, false),
('mu', 'Mauritius', 'east', 'MUR', false, true, false, false),
('ma', 'Morocco', 'north', 'MAD', false, true, false, false),
('mz', 'Mozambique', 'south', 'MZN', false, true, false, false),
('na', 'Namibia', 'south', 'NAD', false, true, false, false),
('ne', 'Niger', 'west', 'XOF', false, true, false, false),
('ng', 'Nigeria', 'west', 'NGN', true, true, true, false),
('cg', 'Republic of the Congo', 'central', 'XAF', false, true, false, false),
('rw', 'Rwanda', 'east', 'RWF', false, true, false, false),
('st', 'São Tomé and Príncipe', 'central', 'STN', false, true, false, false),
('sn', 'Senegal', 'west', 'XOF', true, true, true, false),
('sc', 'Seychelles', 'east', 'SCR', false, true, false, false),
('sl', 'Sierra Leone', 'west', 'SLE', true, true, true, false),
('so', 'Somalia', 'east', 'SOS', false, true, false, false),
('za', 'South Africa', 'south', 'ZAR', false, true, false, false),
('ss', 'South Sudan', 'east', 'SSP', false, true, false, false),
('sd', 'Sudan', 'east', 'SDG', false, true, false, false),
('tz', 'Tanzania', 'east', 'TZS', false, true, false, false),
('gm', 'The Gambia', 'west', 'GMD', true, true, true, false),
('tg', 'Togo', 'west', 'XOF', true, true, true, false),
('tn', 'Tunisia', 'north', 'TND', false, true, false, false),
('ug', 'Uganda', 'east', 'UGX', false, true, false, false),
('eh', 'Western Sahara', 'north', 'MAD', false, true, false, false),
('zm', 'Zambia', 'south', 'ZMW', false, true, false, false),
('zw', 'Zimbabwe', 'south', 'ZWG', false, true, false, false)
on conflict (iso2) do nothing;
